trigger:
- '*'

pr:
- '*'

variables:
- group: GitConfigVariables

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    steps:
    - checkout: self  # Check out the source code

    - script: |
        echo 'Building...'
        pip install -r requirements.txt  # Install project dependencies

        echo 'Running unittest...'
        python -m unittest discover -s test -p '*_test.py'

        echo 'Running pytest...'
        pip install -r requirements-test.txt  # Install test dependencies
        pytest -s test
      displayName: 'Build and Test'

- stage: ManualIntervention
  jobs:
  - deployment: ManualInterventionJob
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'ManualStage'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: echo "Waiting for manual intervention..."
            displayName: 'Manual Intervention'



  - job: MergeToMain
    displayName: 'Merge to Main - $(Build.SourceBranchName)'

    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/pull/$(System.PullRequest.PullRequestId)/merge'))
    steps:
    - checkout: self  # Check out the main branch for the merge
    - script: |
        echo 'Merging to main...'
        git config user.email "$(GIT_USER_EMAIL)"
        git config user.name "$(GIT_USER_NAME)"
        git checkout main
        git merge --no-ff --no-edit $(System.PullRequest.SourceBranch)
        git push origin main
      displayName: 'Merge to Main'
